### ISSUE TITLE
Concrete Exists type

### ISSUE THREAD

**Issue by sorenbug** [alexknvl/polymorphic#4]
I recently had to create my own Exists:
```scala
trait Exists[F[_]] {

  type T

  val value: F[T]

}

object Exists {

  def apply[F[_], A](fa: F[A]): Exists[F] = new Exists[F] {
    type T = A
    override val value: F[A] = fa
  }

}
```
as the builtin exists type didn't have a `.value` and broke the inner with needing to use `unapply`.

I'm currently using this form of Exists with scodec a _little_ bit like so:
```scala
trait Format[A] {
  val code: BitVector
  val codec: Codec[A]
}
```
```scala
val formats: Vector[Exists[Format]] = Vector(
  formatA,
  formatB
)
```
```scala
scodec.codecs.choice[Instance[Format]](
  formats.map { f =>
    scodec.codecs.constant(f.value.code) ~>
      f.value.codec.xmapc(Instance.capture(_)(f))(_.first.asInstanceOf)
  }: _*
)
```
Is there a reason polymorphic's Exist is a newtype and not like this one? Is there an obvious language feature I'm overlooking that accomplishes what I'm doing with my own `Exists`?

**Comment by alexknvl** [comment]
It does expose `value` through https://github.com/alexknvl/polymorphic/blob/master/src/main/scala/polymorphic/syntax/ExistsSyntax.scala#L7. The only reason it is a newtype is because that allows to avoid a level of indirection.

**Comment by sorenbug** [comment]
Huh. I must not have imported the right thing. Will check when I get home.

**Comment by sorenbug** [comment]
Yeah, `import polymorphic.syntax.exists._` works. My bad.
